name: Generate Garmin Secret

on:
  workflow_dispatch:
    inputs:
      email:
        description: "你的佳明账号邮箱"
        required: true
      password:
        description: "你的佳明密码"
        required: true
      is_cn:
        description: "是否为国行账号？(国际区请务必不要勾选)"
        required: true
        type: boolean
        default: false

jobs:
  get_secret:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Get Secret
        run: |
          if [ "${{ github.event.inputs.is_cn }}" = "true" ]; then
             python run_page/get_garmin_secret.py "${{ github.event.inputs.email }}" "${{ github.event.inputs.password }}" --is-cn
          else
             python run_page/get_garmin_secret.py "${{ github.event.inputs.email }}" "${{ github.event.inputs.password }}"
          fi
